FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

EXPOSE 4173

# Note the -- --host 0.0.0.0 to expose to network
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]