services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: todo-frontend-prod
    restart: unless-stopped
    networks:
      - frontend-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - frontend-net
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: todo-backend-prod
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/todo-app
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - backend-net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb-prod
    volumes:
      - mongodb_data:/data/db
    expose:
      - "27017"
    networks:
      - backend-net
    restart: unless-stopped
    command: [ "mongod", "--auth" ]

networks:
  frontend-net:
  backend-net:


volumes:
  mongodb_data:
